version: "3.8"
services:
  redis:
    image: redis:7.2.5
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: >
      redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch.Dockerfile
    container_name: my-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # 보안 설정 (운영 모드에서는 true로 변경)
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # 운영 모드에서는 메모리 사용량 조정
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./src/main/resources/elasticsearch/synonyms.txt:/usr/share/elasticsearch/config/analysis/synonyms.txt:ro
      - ./src/main/resources/elasticsearch/user_dictionary.txt:/usr/share/elasticsearch/config/analysis/user_dictionary.txt:ro
    restart: unless-stopped
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.3
    container_name: my-kibana
    ports:
      - "5601:5601"
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  redis-data:
  es_data:

networks:
  elastic: