spring:
  datasource:
    url: "jdbc:mysql://mysql_1:3306/${SPRING__DATASOURCE__URL___DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
    username: lldjlocal
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: redis_1
      password: ${SPRING__DATA__REDIS__PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  access_token_expiration_minutes: ${JWT_ACCESS_TOKEN_EXPIRATION:30}
  refresh_token_expiration_days: ${JWT_REFRESH_TOKEN_EXPIRATION:7}

file:
  upload:
    path: /data
    base-url: https://api.bid-market.shop/uploads
testdata:
  generation:
    enabled: false

server:
  port: 8080