spring:
  application:
    name: backend
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB            # 개별 파일 최대 크기
      max-request-size: 25MB        # 전체 요청 최대 크기 (5MB × 5개 = 25MB)
      file-size-threshold: 2KB      # 메모리 임계값
      location: ${java.io.tmpdir}   # 임시 파일 저장 위치

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100 # N+1 문제 해결
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

pg:
  toss:
    clientKey: ${PG_TOSS_CLIENT_KEY}
    secretKey: ${PG_TOSS_SECRET_KEY}

springdoc:
  default-produces-media-type: application/json;charset=UTF-8