spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRepositoriesAutoConfiguration

  datasource:
    url: "jdbc:mysql://mysql_1:3306/${SPRING_DATASOURCE_URL___DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
    username: lldjlocal
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: redis_1
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD}
      lettuce:
        pool:
          enabled: true

  elasticsearch:
    uris: http://elasticsearch_1:9200
    username: elastic
    password: ${SPRING_DATA_REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  access_token_expiration_minutes: ${JWT_ACCESS_TOKEN_EXPIRATION:30}
  refresh_token_expiration_days: ${JWT_REFRESH_TOKEN_EXPIRATION:7}

file:
  upload:
    path: /data
    base-url: https://api.bid-market.shop/uploads
    s3:
      bucket: team12-bid-market-bucket
      base-url: https://team12-bid-market-bucket.s3.ap-northeast-2.amazonaws.com
testdata:
  generation:
    enabled: false

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

app:
  cookie:
    domain: ".bid-market.shop"
    secure: true
    sameSite: Lax