spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET}
  access_token_expiration_minutes: ${JWT_ACCESS_TOKEN_EXPIRATION:30}
  refresh_token_expiration_days: ${JWT_REFRESH_TOKEN_EXPIRATION:7}

file:
  upload:
    path: ${user.home}/uploads
    base-url: https://api.bid-market.shop/uploads
testdata:
  generation:
    enabled: false

server:
  port: 8080